name: id-pipelines

trigger:
  branches:
    include:
    - main

pool:
  name: selfhosted

parameters:
  - name: serviceConnectionName
    type: string
    default: 'id-root'

variables:
  - name: location
    value: 'swedencentral'
  - name: parameterFile
    value: 'main.bicepparam'

stages:
- stage: 
  jobs:
  - job:
    displayName: 'Deploy root identities'
    steps:
      - script: echo $(location)
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ parameters.serviceConnectionName }}
          scriptType: bash
          scriptLocation: 'inlineScript' #| 'scriptPath'
          # scriptPath: 
          #arguments: 
          inlineScript: |
            az --version
            pwd
            az deployment sub create --location ${{ variables.parameterFile }} --parameters ${{ variables.parameterFile }}
          powerShellErrorActionPreference: 'stop' # | 'continue' | 'silentlyContinue'
